Repository work-teams/software-quality, pull requests merged in 2021-08, with the labels that each got.

#45 Controlador ventas
  database/categoria.sql
  database/cliente.sql
  database/database.sql
  database/pedido.sql
  database/producto.sql
  database/proveedores.sql
  database/usuarios.sql
  src/aplicacion/BikeShop.java
  src/controlador/ControladorGeneral.java
  src/controlador/ControladorVenta.java
  src/modelo/dao/ClienteDAO.java
  src/modelo/dao/PedidoDAO.java
  src/modelo/dao/UsuarioDAO.java
  src/modelo/dao/VentaDAO.java
  src/modelo/vo/Pedido.java
  src/modelo/vo/Venta.java
  src/vista/PanelVentas.form
  src/vista/PanelVentas.java
  src/vista/VentanaPrincipal.form
  src/vista/VentanaPrincipal.java
  test/test/TestClienteDAO.java
  test/test/TestControladorVentas.java
  test/test/TestPanelUsuarios.java
Labels: Implement

#46 Estandariza clases DAO
  src/aplicacion/BikeShop.java
  src/controlador/ControladorProducto.java
  src/controlador/ControladorProveedor.java
  src/modelo/ConexionDB.java
  src/modelo/dao/CategoriaDAO.java
  src/modelo/dao/ClienteDAO.java
  src/modelo/dao/PedidoDAO.java
  src/modelo/dao/ProductoDAO.java
  src/modelo/dao/ProveedorDAO.java
  src/modelo/dao/UsuarioDAO.java
  src/modelo/dao/VentaDAO.java
  src/modelo/vo/Categoria.java
  src/vista/PanelProducto.java
  test/test/TestClienteDAO.java
  test/test/TestControladorVentas.java
  test/test/TestPanelProductos.java
  test/test/TestPanelProveedor.java
  test/test/TestPanelUsuarios.java
  test/test/TestPanels.form
  test/test/TestPanels.java
  test/test/dump
Labels: enhancement

#47 Refactoriza clases controlador y paneles
  database/productos.sql
  src/aplicacion/BikeShop.java
  src/controlador/ControladorGeneral.java
  src/controlador/ControladorProducto.java
  src/controlador/ControladorProveedor.java
  src/controlador/ControladorUsuario.java
  src/controlador/ControladorVenta.java
  src/modelo/dao/ProductoDAO.java
  src/modelo/vo/Categoria.java
  src/modelo/vo/Cliente.java
  src/modelo/vo/Pedido.java
  src/modelo/vo/Producto.java
  src/modelo/vo/Proveedor.java
  src/modelo/vo/Usuario.java
  src/modelo/vo/Venta.java
  src/vista/PanelProducto.form
  src/vista/PanelProducto.java
  src/vista/PanelProveedores.form
  src/vista/PanelProveedores.java
  src/vista/PanelUsuarios.form
  src/vista/PanelUsuarios.java
  src/vista/PanelVentas.form
  src/vista/PanelVentas.java
Labels: enhancement

#48 Diseña panel historial de ventas y cliente
  src/vista/PanelClientes.form
  src/vista/PanelClientes.java
  src/vista/PanelHistorialVentas.form
  src/vista/PanelHistorialVentas.java
Labels: design, enhancement

#50 Parcha error en controlador producto
  src/aplicacion/BikeShop.java
  src/vista/PanelProducto.java
Labels: hotfix

#51 Design ventana principal
  src/aplicacion/BikeShop.java
  src/controlador/ControladorGeneral.java
  src/recursos/cliente.png
  src/recursos/cliente_full.png
  src/recursos/cliente_hand.png
  src/recursos/historial.png
  src/recursos/valor.png
  src/vista/VentanaPrincipal.form
  src/vista/VentanaPrincipal.java
Labels: design, enhancement

#55 Agrega botón home y logout
  src/controlador/ControladorGeneral.java
  src/recursos/home.png
  src/recursos/logout.png
  src/vista/VentanaPrincipal.form
  src/vista/VentanaPrincipal.java
Labels: enhancement

#53 Controladores de los paneles cliente e historial ventas
  src/aplicacion/BikeShop.java
  src/controlador/ControladorCliente.java
  src/controlador/ControladorGeneral.java
  src/controlador/ControladorHistorialVenta.java
  src/vista/PanelClientes.form
  src/vista/PanelClientes.java
  src/vista/PanelHistorialVentas.form
  src/vista/PanelHistorialVentas.java
  src/vista/PanelProducto.java
  src/vista/PanelVentas.java
Labels: feature

#59 Diseña interfaz gráfica del login
  src/imagenes/imgHold.png
  src/vista/VentanaLogin.form
  src/vista/VentanaLogin.java
Labels: design, enhancement

#61 Controlador login
  src/aplicacion/BikeShop.java
  src/controlador/ControladorGeneral.java
  src/controlador/ControladorLogin.java
  src/controlador/ControladorUsuario.java
  src/controlador/ControladorVenta.java
  src/modelo/dao/CategoriaDAO.java
  src/modelo/dao/ClienteDAO.java
  src/modelo/dao/PedidoDAO.java
  src/modelo/dao/ProductoDAO.java
  src/modelo/dao/ProveedorDAO.java
  src/modelo/dao/UsuarioDAO.java
  src/modelo/dao/VentaDAO.java
  src/vista/PanelClientes.form
  src/vista/PanelClientes.java
  src/vista/PanelHistorialVentas.form
  src/vista/PanelHistorialVentas.java
  src/vista/PanelProducto.form
  src/vista/PanelProducto.java
  src/vista/PanelProveedores.java
  src/vista/PanelUsuarios.java
  src/vista/PanelVentas.form
  src/vista/PanelVentas.java
  src/vista/VentanaLogin.form
  src/vista/VentanaLogin.java
  src/vista/VentanaPrincipal.form
  src/vista/VentanaPrincipal.java
Labels: Implement, hotfix

#63 Desing medidas
  src/controlador/ControladorGeneral.java
  src/vista/PanelClientes.form
  src/vista/PanelClientes.java
  src/vista/PanelHistorialVentas.form
  src/vista/PanelHistorialVentas.java
  src/vista/PanelProducto.form
  src/vista/PanelProducto.java
  src/vista/PanelProveedores.form
  src/vista/PanelProveedores.java
  src/vista/PanelUsuarios.form
  src/vista/PanelUsuarios.java
  src/vista/PanelVentas.form
  src/vista/PanelVentas.java
  src/vista/VentanaLogin.form
  src/vista/VentanaLogin.java
  src/vista/VentanaPrincipal.form
  src/vista/VentanaPrincipal.java
Labels: enhance, design

#68 Enchance focus event
  src/controlador/ControladorProducto.java
  src/controlador/ControladorProveedor.java
  src/controlador/ControladorUsuario.java
  src/vista/PanelProducto.form
  src/vista/PanelProducto.java
  src/vista/PanelProveedores.form
  src/vista/PanelProveedores.java
  src/vista/PanelUsuarios.form
  src/vista/PanelUsuarios.java
Labels: enhance
